import 'package:falcon_system/data/models/admin_profile.dart';
import 'package:falcon_system/data/models/aerodrome.dart';
import 'package:falcon_system/data/models/aircraft.dart';
import 'package:falcon_system/data/models/airport_manager.dart';
import 'package:falcon_system/data/models/evaluation_report.dart';
import 'package:falcon_system/data/models/inspection_head.dart';
import 'package:falcon_system/data/models/inspection_member.dart';
import 'package:hive_flutter/hive_flutter.dart';

import '../constants/hive_keys.dart';

class HiveService {
  static bool _initialized = false;

  static Future<void> init() async {
    if (_initialized) return;

    // Initialize Hive
    await Hive.initFlutter();

    // Register all adapters
    _registerAdapters();

    // Open all boxes
    await _openBoxes();

    _initialized = true;
  }

  static void _registerAdapters() {
    // Register adapters for all HiveObject models
    // Note: These adapters will be generated by build_runner
    // Run: flutter pub run build_runner build --delete-conflicting-outputs
    Hive.registerAdapter(AdminProfileAdapter());
    Hive.registerAdapter(AerodromeAdapter());
    Hive.registerAdapter(AirportManagerAdapter());
    Hive.registerAdapter(InspectionHeadAdapter());
    Hive.registerAdapter(InspectionMemberAdapter());
    Hive.registerAdapter(AircraftAdapter());
    Hive.registerAdapter(EvaluationReportAdapter());
  }

  static Future<void> _openBoxes() async {
    // Open all boxes
    await Hive.openBox<dynamic>(HiveKeys.adminProfileBox);
    await Hive.openBox<dynamic>(HiveKeys.aerodromesBox);
    await Hive.openBox<dynamic>(HiveKeys.airportManagersBox);
    await Hive.openBox<dynamic>(HiveKeys.inspectionHeadBox);
    await Hive.openBox<dynamic>(HiveKeys.inspectionTeamBox);
    await Hive.openBox<dynamic>(HiveKeys.aircraftBox);
    await Hive.openBox<dynamic>(HiveKeys.evaluationReportsBox);
  }

  static Future<void> close() async {
    await Hive.close();
    _initialized = false;
  }

  static Future<void> clearAll() async {
    await Hive.deleteBoxFromDisk(HiveKeys.adminProfileBox);
    await Hive.deleteBoxFromDisk(HiveKeys.aerodromesBox);
    await Hive.deleteBoxFromDisk(HiveKeys.airportManagersBox);
    await Hive.deleteBoxFromDisk(HiveKeys.inspectionHeadBox);
    await Hive.deleteBoxFromDisk(HiveKeys.inspectionTeamBox);
    await Hive.deleteBoxFromDisk(HiveKeys.aircraftBox);
    await Hive.deleteBoxFromDisk(HiveKeys.evaluationReportsBox);
  }

  // Box getters
  static Box<dynamic> get adminBox => Hive.box(HiveKeys.adminProfileBox);
  static Box<dynamic> get aerodromeBox => Hive.box(HiveKeys.aerodromesBox);
  static Box<dynamic> get managerBox => Hive.box(HiveKeys.airportManagersBox);
  static Box<dynamic> get inspectionHeadBox =>
      Hive.box(HiveKeys.inspectionHeadBox);
  static Box<dynamic> get inspectionMemberBox =>
      Hive.box(HiveKeys.inspectionTeamBox);
  static Box<dynamic> get aircraftBox => Hive.box(HiveKeys.aircraftBox);
  static Box<dynamic> get evaluationBox =>
      Hive.box(HiveKeys.evaluationReportsBox);

  // Admin Profile methods
  static AdminProfile? getAdminProfile() {
    return adminBox.get('admin') as AdminProfile?;
  }

  static Future<void> saveAdminProfile(AdminProfile profile) async {
    await adminBox.put('admin', profile);
  }
}
