import 'package:falcon_system/data/models/aerodrome.dart';
import 'package:uuid/uuid.dart';

/// ─────────────────────────────────────────────────────────────────────────
/// AerodromeSeed
/// بيانات مطارات جمهورية مصر العربية — يُستخدم عند أول تشغيل للتطبيق
/// ─────────────────────────────────────────────────────────────────────────
class AerodromeSeed {
  AerodromeSeed._();

  static const _uuid = Uuid();

  static List<Aerodrome> get egyptianAerodromes => [
    // ══════════════════════════════════════════════════════════════════
    //  مطارات مدنية
    // ══════════════════════════════════════════════════════════════════
    _make(
      icao: 'HECA',
      arabic: 'مطار القاهرة الدولي',
      english: 'Cairo International Airport',
      type: 'مدني',
      governorate: 'القاهرة',
      city: 'القاهرة',
      lat: 30.1219,
      lon: 31.4056,
      elevation: 116,
      status: 'نشط',
      reg: 'EG-CA-001',
      operator: 'شركة مطارات القاهرة',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4F',
      runway: 4000,
      capacity: 30,
      created: DateTime(1963, 3, 29),
      inspected: DateTime(2024, 11, 1),
      notes: 'أكبر مطارات مصر وأكثرها ازدحامًا — يخدم القاهرة الكبرى',
    ),
    _make(
      icao: 'HEAX',
      arabic: 'مطار برج العرب الدولي',
      english: 'Borg El Arab International Airport',
      type: 'مدني',
      governorate: 'الإسكندرية',
      city: 'الإسكندرية',
      lat: 30.9176,
      lon: 29.6964,
      elevation: 45,
      status: 'نشط',
      reg: 'EG-AL-001',
      operator: 'الهيئة المصرية للطيران المدني',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4E',
      runway: 3350,
      capacity: 15,
      created: DateTime(1997, 6, 1),
      inspected: DateTime(2024, 10, 15),
      notes: 'المطار الرئيسي لمحافظة الإسكندرية',
    ),
    _make(
      icao: 'HESH',
      arabic: 'مطار شرم الشيخ الدولي',
      english: 'Sharm El Sheikh International Airport',
      type: 'مدني',
      governorate: 'جنوب سيناء',
      city: 'شرم الشيخ',
      lat: 27.9773,
      lon: 34.3950,
      elevation: 54,
      status: 'نشط',
      reg: 'EG-SS-001',
      operator: 'الهيئة المصرية للطيران المدني',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4E',
      runway: 3800,
      capacity: 12,
      created: DateTime(1975, 1, 1),
      inspected: DateTime(2024, 9, 20),
      notes: 'أحد أهم مطارات السياحة الدولية',
    ),
    _make(
      icao: 'HEGN',
      arabic: 'مطار الغردقة الدولي',
      english: 'Hurghada International Airport',
      type: 'مدني',
      governorate: 'البحر الأحمر',
      city: 'الغردقة',
      lat: 27.1783,
      lon: 33.7994,
      elevation: 15,
      status: 'نشط',
      reg: 'EG-HG-001',
      operator: 'الهيئة المصرية للطيران المدني',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4E',
      runway: 4000,
      capacity: 12,
      created: DateTime(1966, 1, 1),
      inspected: DateTime(2024, 10, 5),
      notes: 'بوابة البحر الأحمر السياحية',
    ),
    _make(
      icao: 'HELX',
      arabic: 'مطار الأقصر الدولي',
      english: 'Luxor International Airport',
      type: 'مدني',
      governorate: 'الأقصر',
      city: 'الأقصر',
      lat: 25.6710,
      lon: 32.7066,
      elevation: 93,
      status: 'نشط',
      reg: 'EG-LX-001',
      operator: 'الهيئة المصرية للطيران المدني',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4D',
      runway: 3300,
      capacity: 8,
      created: DateTime(1952, 1, 1),
      inspected: DateTime(2024, 8, 10),
      notes: 'بوابة آثار الأقصر العالمية',
    ),
    _make(
      icao: 'HEAS',
      arabic: 'مطار أسوان الدولي',
      english: 'Aswan International Airport',
      type: 'مدني',
      governorate: 'أسوان',
      city: 'أسوان',
      lat: 23.9644,
      lon: 32.8200,
      elevation: 209,
      status: 'نشط',
      reg: 'EG-AS-001',
      operator: 'الهيئة المصرية للطيران المدني',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4D',
      runway: 3200,
      capacity: 6,
      created: DateTime(1960, 1, 1),
      inspected: DateTime(2024, 7, 22),
    ),
    _make(
      icao: 'HEKN',
      arabic: 'مطار أسيوط الدولي',
      english: 'Asyut International Airport',
      type: 'مدني',
      governorate: 'أسيوط',
      city: 'أسيوط',
      lat: 27.0465,
      lon: 31.0120,
      elevation: 74,
      status: 'نشط',
      reg: 'EG-AY-001',
      operator: 'الهيئة المصرية للطيران المدني',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4D',
      runway: 3200,
      capacity: 5,
      created: DateTime(1968, 1, 1),
      inspected: DateTime(2024, 6, 15),
    ),
    _make(
      icao: 'HESK',
      arabic: 'مطار سوهاج الدولي',
      english: 'Sohag International Airport',
      type: 'مدني',
      governorate: 'سوهاج',
      city: 'سوهاج',
      lat: 26.3428,
      lon: 31.7428,
      elevation: 72,
      status: 'نشط',
      reg: 'EG-SH-001',
      operator: 'الهيئة المصرية للطيران المدني',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4D',
      runway: 3200,
      capacity: 4,
      created: DateTime(2010, 1, 1),
      inspected: DateTime(2024, 5, 10),
    ),
    _make(
      icao: 'HESN',
      arabic: 'مطار سفنكس الدولي',
      english: 'Sphinx International Airport',
      type: 'مدني',
      governorate: 'الجيزة',
      city: 'السادس من أكتوبر',
      lat: 30.1076,
      lon: 30.9008,
      elevation: 55,
      status: 'نشط',
      reg: 'EG-GZ-002',
      operator: 'الهيئة المصرية للطيران المدني',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4E',
      runway: 4000,
      capacity: 10,
      created: DateTime(2019, 1, 1),
      inspected: DateTime(2024, 11, 20),
      notes: 'مطار دولي حديث يخدم غرب القاهرة الكبرى',
    ),
    _make(
      icao: 'HETR',
      arabic: 'مطار مرسى مطروح',
      english: 'Marsa Matruh Airport',
      type: 'مدني',
      governorate: 'مطروح',
      city: 'مرسى مطروح',
      lat: 31.3244,
      lon: 27.2216,
      elevation: 94,
      status: 'نشط',
      reg: 'EG-MT-001',
      operator: 'الهيئة المصرية للطيران المدني',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4D',
      runway: 3000,
      capacity: 4,
      created: DateTime(1958, 1, 1),
      inspected: DateTime(2024, 4, 30),
    ),
    _make(
      icao: 'HEOW',
      arabic: 'مطار أبو سمبل',
      english: 'Abu Simbel Airport',
      type: 'مدني',
      governorate: 'أسوان',
      city: 'أبو سمبل',
      lat: 22.3760,
      lon: 31.6119,
      elevation: 195,
      status: 'نشط',
      reg: 'EG-AS-002',
      operator: 'الهيئة المصرية للطيران المدني',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4C',
      runway: 2750,
      capacity: 2,
      created: DateTime(1974, 1, 1),
      inspected: DateTime(2024, 3, 15),
      notes: 'يخدم زوار معبد أبو سمبل الأثري',
    ),
    _make(
      icao: 'HETB',
      arabic: 'مطار طابا الدولي',
      english: 'Taba International Airport',
      type: 'مدني',
      governorate: 'جنوب سيناء',
      city: 'طابا',
      lat: 29.5878,
      lon: 34.7758,
      elevation: 9,
      status: 'نشط',
      reg: 'EG-TB-001',
      operator: 'الهيئة المصرية للطيران المدني',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4D',
      runway: 2758,
      capacity: 3,
      created: DateTime(1989, 1, 1),
      inspected: DateTime(2024, 2, 20),
    ),
    _make(
      icao: 'HESG',
      arabic: 'مطار سانت كاترين الدولي',
      english: 'Saint Catherine International Airport',
      type: 'مدني',
      governorate: 'جنوب سيناء',
      city: 'سانت كاترين',
      lat: 28.6853,
      lon: 34.0625,
      elevation: 1497,
      status: 'نشط',
      reg: 'EG-SC-001',
      operator: 'الهيئة المصرية للطيران المدني',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4C',
      runway: 2751,
      capacity: 2,
      created: DateTime(1983, 1, 1),
      inspected: DateTime(2023, 12, 10),
      notes: 'أعلى مطار في مصر فوق مستوى سطح البحر',
    ),
    _make(
      icao: 'HEMK',
      arabic: 'مطار المنيا',
      english: 'El Minya Airport',
      type: 'مدني',
      governorate: 'المنيا',
      city: 'المنيا',
      lat: 28.0961,
      lon: 30.7244,
      elevation: 59,
      status: 'مغلق مؤقتاً',
      reg: 'EG-MN-001',
      operator: 'الهيئة المصرية للطيران المدني',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4C',
      runway: 2750,
      capacity: 2,
      created: DateTime(1955, 1, 1),
      inspected: DateTime(2022, 6, 1),
    ),
    _make(
      icao: 'HEQN',
      arabic: 'مطار قنا',
      english: 'Qena Airport',
      type: 'مدني',
      governorate: 'قنا',
      city: 'قنا',
      lat: 26.7503,
      lon: 32.7850,
      elevation: 80,
      status: 'نشط',
      reg: 'EG-QN-001',
      operator: 'الهيئة المصرية للطيران المدني',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4C',
      runway: 2700,
      capacity: 2,
      created: DateTime(1960, 1, 1),
      inspected: DateTime(2024, 1, 15),
    ),

    // ══════════════════════════════════════════════════════════════════
    //  مطارات عسكرية
    // ══════════════════════════════════════════════════════════════════
    _make(
      icao: 'HEBL',
      arabic: 'قاعدة بلبيس الجوية',
      english: 'Bilbeis Air Base',
      type: 'عسكري',
      governorate: 'الشرقية',
      city: 'بلبيس',
      lat: 30.7161,
      lon: 31.5906,
      elevation: 26,
      status: 'نشط',
      reg: 'EG-MIL-BL-001',
      operator: 'القوات الجوية المصرية',
      authority: 'هيئة الطيران العسكري',
      category: '4E',
      runway: 3000,
      capacity: 40,
      created: DateTime(1952, 1, 1),
      inspected: DateTime(2024, 10, 1),
      notes: 'تحتضن مدرسة الطيران العسكري المصرية',
    ),
    _make(
      icao: 'HEAT',
      arabic: 'قاعدة عتاقة الجوية',
      english: 'Ataqa Air Base',
      type: 'عسكري',
      governorate: 'السويس',
      city: 'السويس',
      lat: 30.0803,
      lon: 32.5542,
      elevation: 10,
      status: 'نشط',
      reg: 'EG-MIL-AT-001',
      operator: 'القوات الجوية المصرية',
      authority: 'هيئة الطيران العسكري',
      category: '4E',
      runway: 3000,
      capacity: 30,
      created: DateTime(1955, 1, 1),
      inspected: DateTime(2024, 9, 1),
    ),
    _make(
      icao: 'HEAI',
      arabic: 'قاعدة إنشاص الجوية',
      english: 'Inshas Air Base',
      type: 'عسكري',
      governorate: 'الشرقية',
      city: 'إنشاص',
      lat: 30.5703,
      lon: 31.3997,
      elevation: 17,
      status: 'نشط',
      reg: 'EG-MIL-IN-001',
      operator: 'القوات الجوية المصرية',
      authority: 'هيئة الطيران العسكري',
      category: '4F',
      runway: 3500,
      capacity: 60,
      created: DateTime(1948, 1, 1),
      inspected: DateTime(2024, 8, 15),
      notes: 'من أقدم وأكبر قواعد القوات الجوية المصرية',
    ),
    _make(
      icao: 'HEOC',
      arabic: 'قاعدة القاهرة الغربية الجوية',
      english: 'Cairo West Air Base',
      type: 'عسكري',
      governorate: 'الجيزة',
      city: 'القاهرة الغربية',
      lat: 30.1167,
      lon: 30.9158,
      elevation: 60,
      status: 'نشط',
      reg: 'EG-MIL-CW-001',
      operator: 'القوات الجوية المصرية',
      authority: 'هيئة الطيران العسكري',
      category: '4F',
      runway: 3900,
      capacity: 50,
      created: DateTime(1941, 1, 1),
      inspected: DateTime(2024, 11, 5),
    ),

    // ══════════════════════════════════════════════════════════════════
    //  مطارات مختلطة
    // ══════════════════════════════════════════════════════════════════
    _make(
      icao: 'HEAR',
      arabic: 'مطار العريش الدولي',
      english: 'El Arish International Airport',
      type: 'مختلط',
      governorate: 'شمال سيناء',
      city: 'العريش',
      lat: 31.0733,
      lon: 33.8358,
      elevation: 30,
      status: 'نشط',
      reg: 'EG-AR-001',
      operator: 'الهيئة المصرية للطيران المدني / القوات الجوية',
      authority: 'الهيئة المصرية للطيران المدني',
      category: '4E',
      runway: 3350,
      capacity: 8,
      created: DateTime(1959, 1, 1),
      inspected: DateTime(2024, 7, 1),
      notes: 'يستخدم للأغراض المدنية والعسكرية',
    ),
    _make(
      icao: 'HEBM',
      arabic: 'قاعدة بني سويف الجوية',
      english: 'Beni Suef Air Base',
      type: 'مختلط',
      governorate: 'بني سويف',
      city: 'بني سويف',
      lat: 29.2081,
      lon: 31.0167,
      elevation: 59,
      status: 'نشط',
      reg: 'EG-BS-001',
      operator: 'القوات الجوية المصرية',
      authority: 'هيئة الطيران العسكري',
      category: '4E',
      runway: 3200,
      capacity: 25,
      created: DateTime(1957, 1, 1),
      inspected: DateTime(2024, 6, 20),
      notes: 'قاعدة جوية رئيسية مع إمكانية الاستخدام المدني المحدود',
    ),
  ];

  static Aerodrome _make({
    required String icao,
    required String arabic,
    required String english,
    required String type,
    required String governorate,
    required String city,
    required double lat,
    required double lon,
    required double elevation,
    required String status,
    required String reg,
    required String operator,
    required String authority,
    required String category,
    required double runway,
    required int capacity,
    DateTime? created,
    DateTime? inspected,
    String? notes,
  }) {
    return Aerodrome(
      id: _uuid.v5(Uuid.NAMESPACE_URL, 'hive.aerodrome.$icao'),
      icaoCode: icao,
      arabicName: arabic,
      englishName: english,
      airportType: type,
      governorate: governorate,
      city: city,
      latitude: lat,
      longitude: lon,
      elevation: elevation,
      operationalStatus: status,
      registrationNumber: reg,
      operator: operator,
      supervisingAuthority: authority,
      icaoCategory: category,
      longestRunway: runway,
      capacity: capacity,
      creationDate: created ?? DateTime(1960, 1, 1),
      lastInspection: inspected,
      notes: notes,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );
  }
}
